language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

# Requires a C++11 compiler
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
env:
  - CXX=g++-5

before_install:
  # Using xvfb for headless browser based tests
  # Based on https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  # and https://github.com/electron/electron/blob/master/docs/tutorial/testing-on-headless-ci.md
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - make lint
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)
